title: Stephen Roddy PhD # your name (or website title) here
logo: "/images/38278590_289827491598867_4278751191707418624_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Portfolio of HCI Research and Design Projects.
  <br><br>
  I am a Researcher and Developer working with a background in Human-computer Interaction.
  This portfolio documents some of the HCI projects that I have recently undertaken.
  <br><br>

  <a href="https://www.stephenroddy.com/">View My Website</a>
  <br>
  <a href="https://www.linkedin.com/in/stephenroddy/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
