title: Stephen Roddy PhD # your name (or website title) here
logo: "/images/38278590_289827491598867_4278751191707418624_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Portfolio of HCI Research and Design Projects.
  <br><br>
  I am a Human-computer Interaction Researcher and Developer working at the intersection of Computer Science and the Digital Arts.
  This portfolio documents and showcases some of the HCI projects that I have undertaken in those fields.
  <br><br>

  <a href="https://www.stephenroddy.com/">View My Website</a>
  <br>
  <a href="https://www.linkedin.com/in/stephenroddy/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
