title: Stephen Roddy # your name (or website title) here
logo: "/images/profile2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style="text-align: left;"><a target="_blank" href="https://orcid.org/0000-0001-8491-3031"><img alt="ORCID" height="35" src="/images/links/orcid.png" width="35"></a><a target="_blank" href="https://www.researchgate.net/profile/Stephen_Roddy"><img alt="Research Gate" height="35" src="/images/links/resGate.png" width="35"></a><a target="_blank" href="https://scholar.google.com/citations?user=qhL5rvsAAAAJ"><img alt="Google Scholar" height="35" src="/images/links/gs.png" width="35"></a> <a target="_blank" href="https://www.linkedin.com/in/stephenroddy/"><img alt="LinkedIn" height="35" src="/images/links/linkedin.png" width="35"></a> <a target="_blank" href="https://github.com/StephenRoddy"><img alt="Github" height="35" src="/images/links/Github.png" width="35"></a><a target="_blank" href="https://stephenroddy.bandcamp.com/"><img alt="BandCamp" height="35" src="/images/links/BandCamp.png" width="35"></a></p>
  <p style="text-align: left;">
  “An experimental composer from Ireland, Stephen Roddy proves equally adept at crushing soundscapes as he does mysterious melodies.”
  </p>
  <p style="text-align: right;">
  <i>- Bandcamp New & Notable, March 2022.</i>
  </p>
  <p style="text-align: left;">
  <a href="https://stephenroddy.bandcamp.com/" target="_blank">Sound & Music</a><br />
    <a href="https://stephenroddy.github.io/academic/academic" target="_blank">Academic Work</a><br />
  <a href="https://stephenroddy.github.io/projects">Research Projects</a><br />
  <a href="https://linktr.ee/stephenroddy" target="_blank">Linktree</a><br />
  </p>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



